### ISSUE TITLE
Parser::CurrentRuby#parse converts .'s to &.'s

### ISSUE THREAD

**Issue by fer9305** [whitequark/parser#884] opened 2022-11-09 16:07 UTC
👋 parser newbie here

Is there a way to call the parse method with an expression and convert every .'s to use safe operator? I tried looking at the docs but couldn't find anything, or are we expected to `gsub` the expression to replace it ourselves? 

Like:

```ruby
=> Parser::CurrentRuby.parse("foo.bar", an_option: :csend)
=> s(:csend,
        s(:send, nil, :foo), :bar)
```

**Comment by iliabylich** [comment] 2022-11-09 18:37
No, it's not possible because `send` and `csend` are semantically different nodes.

What are you trying to do? Depending on what you want to get there are multiple options:

1. If you need to rewrite an AST (and do something later with it without touching your source code) there's  a [Parser::AST::Processor](https://www.rubydoc.info/gems/parser/3.1.2.1/Parser/AST/Processor)
2. If you need to change source code there's a [Parser::Source::TreeRewriter](https://www.rubydoc.info/gems/parser/3.1.2.1/Parser/Source/TreeRewriter) (which is used by RuboCop I think for auto-corrections)

**Comment by fer9305** [comment] 2022-11-15 16:36
I think the usage of [Parser::Source::TreeRewriter](https://www.rubydoc.info/gems/parser/3.1.2.1/Parser/Source/TreeRewriter) is what I'm looking for.

Basically I need to change source code from this:

`foo.bar == 15`

over to:

`foo&.bar == 15`

Any suggestions how can I detect the `.` here? I think I could use replace to change it over to `&.` but I'm not sure how to detect it

**Comment by fer9305** [comment] 2022-11-15 17:29
Ok based on the [docs example](https://www.rubydoc.info/gems/parser/Parser/TreeRewriter#insert_before-instance_method) I could detect the `send` node but now I can't replace the '.' 😓 

```
require 'parser/current'

class ReplaceDot < Parser::TreeRewriter
  def on_send(node)
    byebug
  end
end

code = "foo.bar == 15"

ast           = Parser::CurrentRuby.parse code
buffer        = Parser::Source::Buffer.new('(example)', source: code)
rewriter      = ReplaceDot.new

# Rewrite the AST, returns a String with the new form.
puts rewriter.rewrite(buffer, ast)
```

This is what I got in the `node`'s `location`
```
(byebug) node.location
#<Parser::Source::Map::Send:0x000000010902f530 @dot=nil, @selector=#<Parser::Source::Range (string) 8...10>, @end=nil, @begin=nil, @expression=#<Parser::Source::Range (string) 0...13>, @node=s(:send,
  s(:send,
    s(:send, nil, :foo), :bar), :==,
  s(:int, 15))>
```

I think I'd need to change the ranges around the selector's range and try somehow to replace the `dot` ?

**Comment by marcandre** [comment] 2022-11-15 18:38
The easiest might be to write a custom `rubocop` Cop that would autocorrect what you want into something else.

I would recommend asking your followup questions on StackOverflow or similar and reserve issues for actual bug reports.

Good luck

**Comment by iliabylich** [comment] 2022-11-15 19:12
Yes, that's a good idea as well. Rubocop has a [great documentation](https://docs.rubocop.org/rubocop/development.html#autocorrect) for its autocorrect functionality.

If you don't have (and don't want to have) Rubocop you can still do it manually by calling `replace` in your subclass with a proper `range` argument. One of the `parser`'s main goals is to emit correct and complete locations of literally everything:

```ruby
$ ruby-parse -L -e 'foo.bar = 42'
s(:send,
  s(:send, nil, :foo), :bar=,
  s(:int, 42))
foo.bar = 42
   ~ dot
    ~~~ selector
        ~ operator
~~~~~~~~~~~~ expression
s(:send, nil, :foo)
foo.bar = 42
~~~ selector
~~~ expression
s(:int, 42)
foo.bar = 42
          ~~ expression
```

^ here every location of every node is printed, I think you are interested specifically in location of the `dot` in every `send` node. To get a location called `x` from a node you can call `x_l` (so `dot_l` in your case), and then you can pass it to `replace` method.

This is a question, not a bug report or a feature request, and so of course StackOverlow is a better place to ask it. Closing.

**Closed by iliabylich** 2022-11-15 19:12 UTC
