### ISSUE TITLE
Unable to parse strings with binary encoding in UTF-8 files

### ISSUE THREAD

**Issue by gmalette** [whitequark/parser#533] opened 2018-11-20 15:59 UTC
`Parser` fails to parse ActiveSupport [`Digest::UUID::DNS_NAMESPACE`](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activesupport/lib/active_support/core_ext/digest/uuid.rb#L7). The value of the constant is a binary byte sequence expressed as a String literal. The file is encoded in UTF-8, and `Parser` attempts to validate the string encoding, which fails. The `DNS_NAMESPACE` byte sequence is never used as a String, and `Parser` should not do anything with it's encoding; it shouldn't validate the encoding nor try to re-encode the string.

I trust that the string encoding manipulation of `Parser` came about for good reasons, and if you could enlighten me about them I would really appreciate. Without this information, I don't think I can make a good pull request to fix this issue.

**Comment by whitequark** [comment] 2018-11-20 18:56
Duplicate of https://github.com/whitequark/parser/issues/323, see that issue for a workaround.

**Comment by gmalette** [comment] 2018-11-22 13:20
Thanks for the workaround

**Comment by iliabylich** [comment] 2019-06-17 19:19
@whitequark Can we close it?

**Closed** 2019-06-17 20:47 UTC
Labels: duplicate
