### ISSUE TITLE
Syntax error when there are some do-block in hash. 

### ISSUE THREAD

**Issue by tuchida** [whitequark/parser#353] opened 2017-06-16 04:54 UTC
https://github.com/bbatsov/rubocop/issues/4522

a.rb

```ruby
# frozen_string_literal: true

a = [1, 2, 3]

puts b: {
  c: a.map do |n|
    n * 2
  end,
  d: a.map do |n|
    n * 3
  end,
}
```

```sh
$ ruby a.rb
{:b=>{:c=>[2, 4, 6], :d=>[3, 6, 9]}}
```

```sh
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

```sh
$ rubocop a.rb 
E

Offenses:

a.rb:9:12: E: unexpected token kDO_BLOCK
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
  d: a.map do |n|
           ^^
a.rb:11:3: E: unexpected token kEND
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
  end,
  ^^^

1 file inspected, 2 offenses detected
```

I was taught that this is a problem of parser.

**Comment by whitequark** [comment] 2017-06-16 05:14
*sigh* what a disaster

**Comment by whitequark** [comment] 2017-06-16 05:19
Duplicate of #336.

**Closed by whitequark** 2017-06-16 05:19 UTC
Labels: bug
