### ISSUE TITLE
2.2.3-compliant syntax, but you are running 2.2.4

### ISSUE THREAD

**Issue by spickermann** [whitequark/parser#231] opened 2015-12-17 09:27 UTC
Last night Ruby 2.2.4 was released. I get the following warning now, when I run Rubocop (which include the Parser gem):

    warning: parser/current is loading parser/ruby22, which recognizes
    warning: 2.2.3-compliant syntax, but you are running 2.2.4.
    warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

It seems like [this line](https://github.com/whitequark/parser/blob/896f3f9a4bd9621b25bac1ff3e0df23586d3eac8/lib/parser/current.rb#L45) might need an update. 

I would be happy to help with an PR to fix this. But I am not sure what the right approach is. Do you prefer to warn if someone isn't using the latest version or does it make sense to support multiple version (2.2.3 and 2.2.4)? I do not know why you need this checks and warnings, but it seems a bit labor-intensive if this needs an update every time Ruby was updated. What do you think?

Btw 2.1.7 was also released.

**Comment by whitequark** [comment] 2015-12-17 09:34
Yes, please send a PR updating that line. 2.1.7 is already handled: https://github.com/whitequark/parser/blob/896f3f9a4bd9621b25bac1ff3e0df23586d3eac8/lib/parser/current.rb#L38

The link in the warning describes why this is necessary.

**Comment by spickermann** [comment] 2015-12-17 10:05
Please find the PR here: https://github.com/whitequark/parser/pull/232

**Comment by whitequark** [comment] 2015-12-17 11:07
Hmmm, as if to demonstrate why this shit is necessary: there is in fact a syntax change in 2.2.4! https://github.com/ruby/ruby/commit/df51beda2f3237580976f241842c320b7121d72c

**Comment by whitequark** [comment] 2015-12-17 11:10
Blocked on https://github.com/whitequark/parser/issues/233.

**Comment by spickermann** [comment] 2015-12-17 11:12
Okay, thanks anyway...

**Comment by bbatsov** [comment] 2015-12-18 06:01
> Hmmm, as if to demonstrate why this shit is necessary: there is in fact a syntax change in 2.2.4! ruby/ruby@df51bed

Ruby's team is killing me. Btw, still I think we should issue warnings just for versions that actually introduced syntax changes (after we know there are such changes). Right now people immediately start submitting issues to every project using Parser when new rubies are released, which is pretty annoying.

**Comment by whitequark** [comment] 2015-12-18 06:52
@bbatsov I think I will update the warning (not sure how effective that will be), but I consider not doing it out of question.

**Comment by squaresurf** [comment] 2015-12-18 13:28
So what is the path forward? Is there anything I can do to help?

**Comment by whitequark** [comment] 2015-12-18 13:29
No, you'll have to wait until I have time to fix #233, probably today.

**Comment by squaresurf** [comment] 2015-12-18 13:30
Ok, thank you.

**Comment by chrisnicola** [comment] 2015-12-18 23:38
I'm not sure if this is important but I've noticed the label syntax change seems to go further than "%-string" not being able to be a label.

See this issue: https://github.com/rails/rails/issues/22680 for another example.

Essentially you must have a space between a label and the beginning of a heredoc now, whereas before you didn't need to.

**Comment by whitequark** [comment] 2015-12-19 20:11
@chrisnicola That's horrifying. Also, it further cements my belief that the warning is necessary; unlike some other fairly obscure cases, this is bound to be hit by real-world code.

**Comment by whitequark** [comment] 2015-12-19 20:21
Amazing
![1619](https://cloud.githubusercontent.com/assets/54771/11915070/176ac50e-a6d1-11e5-9472-61977c69b2b2.png)

**Comment by jasnow** [comment] 2015-12-19 20:35
@whitequark - Is there a tool or option to show the "2.2.3-compliant" code in question?

**Comment by whitequark** [comment] 2015-12-19 20:36
@jasnow What do you mean?

**Comment by jasnow** [comment] 2015-12-19 20:45
@whitequark - "Verbose" mode to pinpoint "syntax errors" based on changes to Ruby 2.2.4 syntax so they can be targeted and fixed.

**Comment by whitequark** [comment] 2015-12-19 20:48
Not that I'm aware of. I mean, Ruby 2.2.4 or the next Parser version should effectively do that.

**Comment by whitequark** [comment] 2015-12-19 20:48
(By returning a syntax error, that is.)

**Comment by jasnow** [comment] 2015-12-19 20:50
Or syntax warnings - don't fail "rake" but provide more info.

**Comment by whitequark** [comment] 2015-12-19 20:56
No, this will be an error, as per Parser's Ruby MRI compatibility policy.

**Comment by jasnow** [comment] 2015-12-19 20:59
OK

**Comment by whitequark** [comment] 2015-12-19 22:57
#233 is fixed but I've discovered that I also have to porthttps://github.com/ruby/ruby/commit/94b1db5d673295b4276e809de4937a9536711540 and https://github.com/ruby/ruby/commit/0958af2ad4e83400f35c296e9ed9cf021b1675b4, which are... well, "contrived" is saying it very lightly. So this will take a while.

**Comment by whitequark** [comment] 2015-12-20 00:05
@chrisnicola See https://github.com/whitequark/parser/issues/234.

@bbatsov @mbj You will be entertained by 113442eff, I think.

Everyone else: pre.6 was released with 2.2.4 support.

**Closed by whitequark** 2015-12-20 00:05 UTC

**Comment by jasnow** [comment] 2015-12-20 00:53
pre.6: Applied to all of my affected repos. Worked/Verified. THANKS....

**Comment by nagachika** [comment] 2016-01-04 09:23
Hi, I noticed this thread via comment  on ruby's bug tracker https://bugs.ruby-lang.org/issues/11849#change-55948

I didn't know what the point in this issue well.
BTW I consider the syntax error described at https://github.com/whitequark/parser/issues/231#issuecomment-165921156 is not a intended spec change but a regression. And it was already fixed at trunk and ruby_2_2 branch. Next release 2.2.5 will accept heredoc just after label as 2.2.3 do. I'm sorry for the inconvenience.

Regards,

**Comment by sebasjimenez10** [comment] 2016-03-02 22:22
For those using Rails just used bundler to update the parser gem :smile:
