### ISSUE TITLE
Ruby 2.4.1 Release

### ISSUE THREAD

**Issue by jfly** [whitequark/parser#346] opened 2017-05-05 19:25 UTC
Similar to #344 and #326, we're getting a warning when running Ruby 2.4.1.

```
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

**Comment by whitequark** [comment] 2017-05-06 08:11
See https://github.com/whitequark/parser/pull/342#issuecomment-289304128.

**Comment by bbatsov** [comment] 2017-06-18 10:11
I'll also mention https://github.com/whitequark/parser/issues/317#issuecomment-304316789

TLDR - we need a volunteer for #342.

**Comment by whitequark** [comment] 2017-06-18 10:15
Not just #342 but every Ruby commit that went into 2.3 and 2.4 branches...

**Comment by bbatsov** [comment] 2017-06-18 10:16
I'll post a note in the RuboCop issue tracker regarding this - hopefully it will attract some attention.

**Comment by rubys** [comment] 2017-07-25 03:22
I know that prior issues asking for the ability to silence the warning have been rejected, but there are use cases where support for the latest Ruby language syntax isn't vital, and yet it is worthwhile to stay current on Ruby versions.

**Comment by whitequark** [comment] 2017-07-25 03:25
I'm grinding through several months of backlog that accumulated due to health issues. I'm going to fix Parser *really soon*, it's nearing the head of the queue.

**Comment by rhymes** [comment] 2017-07-29 13:22
@whitequark hope you're feeling better and keep up the great work!

**Comment by whitequark** [comment] 2017-07-29 23:54
Thanks.

**Comment by garrow** [comment] 2017-08-21 16:23
#342 was closed as a duplicate of this issue, but that issue also referenced 
#336 "[Bug #13073]" which has an open PR, #356  "Fix parse error when hash contains do blocks" 
commenting here just to link them together.

**Comment by ayanko** [comment] 2017-09-25 18:44
Any updates about release new gem version?

**Comment by whitequark** [comment] 2017-09-25 20:23
not yet

**Comment by tisba** [comment] 2017-10-12 10:59
Also waiting for this. But I'm also wondering if there should be a new issue for supporting 2.4.2 (released about a month ago)…

**Comment by ayanko** [comment] 2017-10-31 14:49
It's boring message... Let's fix & release :)

**Comment by davidlibrera** [comment] 2017-11-03 10:21
I suppose that we need to wait for christmas

https://github.com/whitequark/parser/commit/0c4462aaa4360c032b2235cb568a73226c54e2c8

**Comment by whitequark** [comment] 2017-11-13 19:12
Will be released once all [blocking-2.4](https://github.com/whitequark/parser/issues?q=is%3Aissue+is%3Aopen+label%3Ablocking-2.4) issues are done.

**Comment by whitequark** [comment] 2018-02-16 15:56
2.5.0.0 has been released.

**Closed by whitequark** 2018-02-16 15:56 UTC
Labels: meta
