### ISSUE TITLE
Dignostics error when parsing regexp ruby accepts:

### ISSUE THREAD

**Issue by mbj** [whitequark/parser#253] opened 2016-01-25 00:22 UTC
The following file (reduced from https://github.com/ruby/spec/blob/master/language/regexp/escapes_spec.rb) is not accepted:

```
# -*- encoding: us-ascii -*-
p /\xAA/
```

Diagnostics error:

```
x.rb:2:3: error: invalid multibyte escape: /\xAA/
x.rb:2: p /\xAA/
x.rb:2:   ^~~~~~

```

Ruby 2.3.0-p0 seems to accept it and prints:

```
/\xAA/
```

**Comment by whitequark** [comment] 2016-01-28 09:48
The root cause is the same as for #252 (there's just a Regexp.new around a parsed string literal), so closing in favor of that one.

**Closed by whitequark** 2016-01-28 09:48 UTC
