### ISSUE TITLE
Single-line pattern matching fails to parse

### ISSUE THREAD

**Issue by palkan** [whitequark/parser#763] opened 2020-11-17 13:21 UTC
Here is the reproduction:

```sh
bundle exec bin/ruby-parse --30 -e '
1 => a
puts a
' -E

1 => a   
^ tINTEGER 1                                    expr_end     [0 <= cond] [0 <= cmdarg] 
  >>> STATE SET <<<                             expr_end     [0 <= cond] [0 <= cmdarg]
1 => a   
  ^~ tASSOC "=>"                                expr_arg     [0 <= cond] [0 <= cmdarg] 
  >>> STATE SET <<<                             expr_beg     [0 <= cond] [0 <= cmdarg]
1 => a   
     ^ tIDENTIFIER "a"                          expr_beg     [0 <= cond] [0 <= cmdarg] (in-kwarg)
puts a   
^~~~ tIDENTIFIER "puts"                         expr_arg     [0 <= cond] [0 <= cmdarg] (in-kwarg)
(fragment:0):3:1: error: unexpected token tIDENTIFIER
(fragment:0):3: puts a
(fragment:0):3: ^~~~  
```

The previous version (with `in`) gives us:

```
bundle exec bin/ruby-parse --27 -e '
1 in a
puts a
' -E
1 in a   
^ tINTEGER 1                                    expr_end     [0 <= cond] [0 <= cmdarg] 
  >>> STATE SET <<<                             expr_end     [0 <= cond] [0 <= cmdarg]
1 in a   
  ^~ kIN "in"                                   expr_value   [0 <= cond] [0 <= cmdarg] 
  >>> STATE SET <<<                             expr_beg     [0 <= cond] [0 <= cmdarg]
1 in a   
     ^ tIDENTIFIER "a"                          expr_arg     [0 <= cond] [0 <= cmdarg] (in-kwarg)
1 in a   
      ^ tNL nil                                 line_begin   [0 <= cond] [0 <= cmdarg] (in-kwarg)
puts a   
^~~~ tIDENTIFIER "puts"                         expr_cmdarg  [0 <= cond] [0 <= cmdarg] 
puts a   
     ^ tIDENTIFIER "a"                          expr_endfn   [0 <= cond] [0 <= cmdarg] 
puts a   
      ^ tNL nil                                 line_begin   [0 <= cond] [1 <= cmdarg] 
   
^ false "$eof"                                  line_begin   [0 <= cond] [0 <= cmdarg] 
(begin
  (in-match
    (int 1)
    (match-var :a))
  (send nil :puts
    (lvar :a)))
```

As far as I understand, the problem is that `tASSOC` transitions to `expr_arg` while `kIN` leads us to `expr_value` (so the right-hand side is treated as `expr_arg`, not as a new expression).

I tried to tweak the lexer but failed to fix the problem in an appropriate time 😞

**Comment by iliabylich** [comment] 2020-11-17 13:29
Good catch. `tNL` is not emitted, and so `expr` of `1 in a` is not reduced into `stmt` and `top_stmt`. Adding `;` after `1 in a` helps, but of course it should be fixed.

I wonder if there are other issues cause by this missing `tNL`. In Ruby `tNL` and `tSEMI` is a separator of statements, and so if we don't emit it things can easily break

**Comment by iliabylich** [comment] 2020-11-23 17:36
ok, finally got some time to debug this issue.

The error comes from the fact that lexer "buffers" tokens. It can read multiple tokens during a single `advance` call, store all of them into a queue and emit one by one later, on the next `#advance` call.

In general it's a great feature, but in Ruby parser modifies lexer's state, and so between `lexer.advance` calls there can be an external (and uncontrollable from the lexer's perspective) state change. I fixed multiple bugs caused by this "feature".

In this case parser sets state to `EXPR_BEG` after `=>` and it expect lexer to emit tIDENT + tNL because of that, but we have tIDENT already processed and stored in the tokens queue from the previous run, and so we restart lexing on `"\n"` and ignore it (because of this EXPR_BEG)

Ideally we should get rid of all `emit(...); fgoto ..` calls and add some kind of a debug assertion (in tests) on the `@token_queue.size`, it shouldn't go above 1. Maybe we should even get rid of `@token_queue`

**Comment by iliabylich** [comment] 2020-11-23 17:38
adding `raise 'err' if @token_queue.any?` to `Lexer#emit` breaks 185 tests, so I'll fix this and start looking at other cases

**Closed** 2020-11-23 18:18 UTC
